### ISSUE TITLE
Question on free look camera

### ISSUE THREAD

**Issue by Tosken1337** [JOML-CI/joml-camera#1]
Hi i have just a question.
In your readme it is stated that you have a free look camera.
It is not implemented yet?
Do you have a example showing of how to use?

Thanks
Sebastian

**Comment by httpdigest** [comment]
Hi Sebastian,
so far I had not yet had time to further joml-camera and to design and assess a possible free look camera implementation.
Much work has been going into the underlying JOML math library recently, which will enable an easy implementation of the free look camera now.
Also, thanks for your post! It gives valuable input to this project that the free look camera is actually desired, and I think a first prototype, which is not much effort thanks to JOML, will be done in the next days. :)

**Comment by Tosken1337** [comment]
Thanks for your reply, 

i really like your joml library. Great work! 
I will look forward to your free look camera implementation. 

Regards
Sebastian

**Comment by dannypurcell** [comment]
:+1: for free look camera

I'm going to spend some time tinkering with the ArcBallCamera anyway, it sounds fun :smile_cat:

**Comment by dannypurcell** [comment]
Btw, if there is a way I can buy you a coffee or something please let me know. JOML is a great piece of work.

**Comment by httpdigest** [comment]
Hi,
hehe, thank you!
Coffee would be nice right now. Preparing the 1.4.0 release of JOML due to tomorrow.
This will be the first version of JOML to be on Maven Central!
Since JOML grew substantially over the last time and contains some rather utility methods/classes, that aren't necessary for the majority of 3D OpenGL applications, there is now a bare-bone `joml-mini` artifact in the 'mini' branch of JOML. This will only contain the most essential classes and methods. Have a look at it.
It will also be deployed as version 1.4.0 tomorrow in Maven Central.
After that, I will take more care of joml-camera. :)

**Comment by httpdigest** [comment]
So it's been two weeks again since the last update that I would work on joml-camera more, but I didn't. :(
During the last two weeks there was just again so much going on with JOML, since that's where the priorities and use cases are right now. I hope I can make a free look camera happen sometime.

**Comment by dannypurcell** [comment]
No worries man. :) 
We're just happy to have someone donating such great work to build a foundation for the rest of us!

I have a couple of ideas I'm tinkering with that might help on that front.
Once I prove them out for myself I'll send them to you to see if you can make use of them.

**Comment by httpdigest** [comment]
It's been quite some time, but it's finally there! A [FreeCamera](https://github.com/JOML-CI/joml-camera/blob/master/src/org/joml/camera/FreeCamera.java). ;)
Have fun with it! :)

**Comment by httpdigest** [comment]
Also there is an [accompanying demo](https://github.com/JOML-CI/joml-lwjgl3-demos/blob/master/src/org/joml/lwjgl/FreeCameraDemo.java).
